# Generated by Django 4.2.4 on 2023-09-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_apply_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
    ]
